"""init schema

Revision ID: 90fbdd7185bd
Revises: 
Create Date: 2026-01-08 10:27:56.228378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90fbdd7185bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('auth_identities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_provider_user')
    )
    op.create_table('closet_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('primary_color', sa.String(length=50), nullable=False),
    sa.Column('secondary_color', sa.String(length=50), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('fabric', sa.String(length=100), nullable=True),
    sa.Column('pattern', sa.String(length=100), nullable=True),
    sa.Column('seasons', postgresql.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.String(length=20), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_closet_items_user_id'), 'closet_items', ['user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_entity_id'), 'jobs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    op.create_table('outfits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outfits_user_id'), 'outfits', ['user_id'], unique=False)
    op.create_table('password_credentials',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('password_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('item_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('closet_item_id', sa.UUID(), nullable=False),
    sa.Column('image_role', sa.String(length=20), nullable=False),
    sa.Column('storage_provider', sa.String(length=30), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('public_url', sa.Text(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_provider', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['closet_item_id'], ['closet_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_images_closet_item_id'), 'item_images', ['closet_item_id'], unique=False)
    op.create_table('outfit_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('outfit_id', sa.UUID(), nullable=False),
    sa.Column('closet_item_id', sa.UUID(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('scale', sa.Float(), nullable=False),
    sa.Column('rotation', sa.Float(), nullable=False),
    sa.Column('z_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['closet_item_id'], ['closet_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outfit_items_closet_item_id'), 'outfit_items', ['closet_item_id'], unique=False)
    op.create_index(op.f('ix_outfit_items_outfit_id'), 'outfit_items', ['outfit_id'], unique=False)
    op.create_table('stylist_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('occasion', sa.String(length=80), nullable=True),
    sa.Column('style_vibe', sa.String(length=80), nullable=True),
    sa.Column('constraints_text', sa.Text(), nullable=True),
    sa.Column('weather_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('prompt_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stylist_requests_job_id'), 'stylist_requests', ['job_id'], unique=False)
    op.create_index(op.f('ix_stylist_requests_user_id'), 'stylist_requests', ['user_id'], unique=False)
    op.create_table('stylist_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stylist_request_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('outfit_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('swap_suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('saved_outfit_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['saved_outfit_id'], ['outfits.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stylist_request_id'], ['stylist_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stylist_results_saved_outfit_id'), 'stylist_results', ['saved_outfit_id'], unique=False)
    op.create_index(op.f('ix_stylist_results_stylist_request_id'), 'stylist_results', ['stylist_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stylist_results_stylist_request_id'), table_name='stylist_results')
    op.drop_index(op.f('ix_stylist_results_saved_outfit_id'), table_name='stylist_results')
    op.drop_table('stylist_results')
    op.drop_index(op.f('ix_stylist_requests_user_id'), table_name='stylist_requests')
    op.drop_index(op.f('ix_stylist_requests_job_id'), table_name='stylist_requests')
    op.drop_table('stylist_requests')
    op.drop_index(op.f('ix_outfit_items_outfit_id'), table_name='outfit_items')
    op.drop_index(op.f('ix_outfit_items_closet_item_id'), table_name='outfit_items')
    op.drop_table('outfit_items')
    op.drop_index(op.f('ix_item_images_closet_item_id'), table_name='item_images')
    op.drop_table('item_images')
    op.drop_table('password_credentials')
    op.drop_index(op.f('ix_outfits_user_id'), table_name='outfits')
    op.drop_table('outfits')
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_entity_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_closet_items_user_id'), table_name='closet_items')
    op.drop_table('closet_items')
    op.drop_table('auth_identities')
    op.drop_table('users')
    # ### end Alembic commands ###
